// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build --deleted-conflicting-outputs
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'archived_messages_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class ArchivedMessagesDto {
  List<int> messageIds;
  List<int> rooms;

  ArchivedMessagesDto({required this.messageIds, required this.rooms});

  factory ArchivedMessagesDto.fromJson(Map<String, dynamic> json) =>
      _$ArchivedMessagesDtoFromJson(json);
  Map<String, dynamic> toJson() => _$ArchivedMessagesDtoToJson(this);
}
