// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build --deleted-conflicting-outputs
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'deleted_messages_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class DeletedMessagesDto {
  List<int> messageIds;

  DeletedMessagesDto({required this.messageIds});

  factory DeletedMessagesDto.fromJson(Map<String, dynamic> json) =>
      _$DeletedMessagesDtoFromJson(json);
  Map<String, dynamic> toJson() => _$DeletedMessagesDtoToJson(this);
}
