// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

import 'message_dto.dart';

part 'messages_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: false,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class MessagesDto {
  int room;
  List<MessageDto> messages;
  int lastMessageId;

  MessagesDto({
    required this.room,
    required this.messages,
    required this.lastMessageId,
  });

  factory MessagesDto.fromJson(Map<String, dynamic> json) =>
      _$MessagesDtoFromJson(json);
// Map<String, dynamic> toJson() => _$MessagesDtoToJson(this);
}
