// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build --delete-conflicting-outputs
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'updated_messages_read_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class UpdatedMessagesReadDto {
  List<UpdatedMessageReadDto> messagesUpdated;

  UpdatedMessagesReadDto({required this.messagesUpdated});

  factory UpdatedMessagesReadDto.fromJson(Map<String, dynamic> json) =>
      _$UpdatedMessagesReadDtoFromJson(json);
  Map<String, dynamic> toJson() => _$UpdatedMessagesReadDtoToJson(this);
}

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class UpdatedMessageReadDto {
  int id;
  List<int> persons_read;
  int room;

  UpdatedMessageReadDto(
      {required this.id, required this.persons_read, required this.room});

  factory UpdatedMessageReadDto.fromJson(Map<String, dynamic> json) =>
      _$UpdatedMessageReadDtoFromJson(json);
  Map<String, dynamic> toJson() => _$UpdatedMessageReadDtoToJson(this);
}
