// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'typing_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class TypingDto {
  String socketId;
  String userName;
  bool typing;

  TypingDto(
      {required this.socketId, required this.userName, required this.typing});

  factory TypingDto.fromJson(Map<String, dynamic> json) =>
      _$TypingDtoFromJson(json);
  Map<String, dynamic> toJson() => _$TypingDtoToJson(this);
}
