// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

import 'person_dto.dart';

part 'persons_found_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PersonsFoundDto {
  List<PersonDto> personsFound;

  PersonsFoundDto({required this.personsFound});

  factory PersonsFoundDto.fromJson(Map<String, dynamic> json) =>
      _$PersonsFoundDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PersonsFoundDtoToJson(this);
}
