// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'person_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PersonDto {
  int id;
  String name;
  String email;
  String phone;
  String username;
  String color;

  PersonDto({
    required this.id,
    required this.name,
    required this.email,
    required this.phone,
    required this.username,
    required this.color,
  });

  factory PersonDto.fromJson(Map<String, dynamic> json) =>
      _$PersonDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PersonDtoToJson(this);
}
