// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'registration_needs_code_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class RegistrationNeedsCodeDto {
  bool emailSent;
  bool smsSent;
  String status;

  RegistrationNeedsCodeDto(
      {required this.status, required this.emailSent, required this.smsSent});

  factory RegistrationNeedsCodeDto.fromJson(Map<String, dynamic> json) =>
      _$RegistrationNeedsCodeDtoFromJson(json);
  Map<String, dynamic> toJson() => _$RegistrationNeedsCodeDtoToJson(this);
}
