// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build --delete-conflicting-outputs
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'delete_messages_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class DeleteMessagesDto {
  List<int> messageIds;
  int user;

  DeleteMessagesDto({required this.messageIds, required this.user});

  factory DeleteMessagesDto.fromJson(Map<String, dynamic> json) =>
      _$DeleteMessagesDtoFromJson(json);
  Map<String, dynamic> toJson() => _$DeleteMessagesDtoToJson(this);
}
