// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import 'package:shopping_list_flutter/network/incoming/pur_item_dto.dart';

part 'edit_purchase_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class EditPurchaseDto {
  int id;
  String name;

  int room;
  int message;

  bool show_pgroup;
  bool show_price;
  bool show_qnty;
  bool show_weight;

  List<int> persons_can_edit;

  List<PurItemDto> purItems;

  EditPurchaseDto({
    required this.id,
    required this.name,
    required this.room,
    required this.message,
    required this.show_pgroup,
    required this.show_price,
    required this.show_qnty,
    required this.show_weight,
    required this.persons_can_edit,
    required this.purItems,
  });

  factory EditPurchaseDto.fromJson(Map<String, dynamic> json) =>
      _$EditPurchaseDtoFromJson(json);
  Map<String, dynamic> toJson() => _$EditPurchaseDtoToJson(this);
}
