// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'get_messages_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: false,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class GetMessagesDto {
  int room;
  int fromMessageId;

  GetMessagesDto({required this.room, required this.fromMessageId});

  // factory GetMessagesDto.fromJson(Map<String, dynamic> json) => _$GetMessagesDtoFromJson(json);
  Map<String, dynamic> toJson() => _$GetMessagesDtoToJson(this);
}
