// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import 'package:shopping_list_flutter/network/incoming/pur_item_dto.dart';

part 'new_purchase_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class NewPurchaseDto {
  String name;

  int room;
  int message;

  bool show_pgroup;
  bool show_price;
  bool show_qnty;
  bool show_weight;

  int? copiedfrom_id;

  int person_created;
  String person_created_name;
  List<int> persons_can_edit;
  bool purchased;
  int? person_purchased;
  String? person_purchased_name;

  double? price_total;
  double? weight_total;

  List<PurItemDto> purItems;

  NewPurchaseDto({
    required this.name,
    required this.room,
    required this.message,
    required this.show_pgroup,
    required this.show_price,
    required this.show_qnty,
    required this.show_weight,
    required this.copiedfrom_id,
    required this.person_created,
    required this.person_created_name,
    required this.persons_can_edit,
    required this.purchased,
    this.person_purchased,
    this.person_purchased_name,
    this.price_total,
    this.weight_total,
    required this.purItems,
  });

  factory NewPurchaseDto.fromJson(Map<String, dynamic> json) =>
      _$NewPurchaseDtoFromJson(json);
  Map<String, dynamic> toJson() => _$NewPurchaseDtoToJson(this);
}
