// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build --delete-conflicting-outputs
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import './new_purchase_dto.dart';

part 'new_message_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class NewMessageDto {
  int room;
  int user;
  String content;
  int? replyto_id;
  NewPurchaseDto? purchase;

  NewMessageDto({
    required this.room,
    required this.user,
    required this.content,
    this.replyto_id,
    this.purchase,
  });

  factory NewMessageDto.fromJson(Map<String, dynamic> json) =>
      _$NewMessageDtoFromJson(json);
  Map<String, dynamic> toJson() => _$NewMessageDtoToJson(this);
}
