// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import 'new_pur_item_dto.dart';

part 'new_purchase_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class NewPurchaseDto {
  String name;

  int room;
  int message;

  bool show_pgroup;
  bool show_qnty;
  bool show_price;
  bool show_weight;
  bool show_state_unknown;
  bool show_state_stop;

  int? copiedfrom_id;

  List<int> persons_can_edit;

  List<NewPurItemDto> newPurItems;

  NewPurchaseDto({
    required this.name,
    required this.room,
    required this.message,
    required this.show_pgroup,
    required this.show_qnty,
    required this.show_price,
    required this.show_weight,
    required this.show_state_unknown,
    required this.show_state_stop,
    required this.copiedfrom_id,
    required this.persons_can_edit,
    required this.newPurItems,
  });

  factory NewPurchaseDto.fromJson(Map<String, dynamic> json) =>
      _$NewPurchaseDtoFromJson(json);
  Map<String, dynamic> toJson() => _$NewPurchaseDtoToJson(this);
}
