// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'new_pur_item_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class NewPurItemDto {
  String name;
  double? qnty;

  String? comment;

  int? pgroup_id;
  String? pgroup_name;

  int? product_id;
  String? product_name;

  int? punit_id;
  String? punit_name;

  String? punit_brief;
  bool? punit_fpoint;

  NewPurItemDto({
    required this.name,
    this.qnty,
    this.comment,
    this.pgroup_id,
    this.pgroup_name,
    this.product_id,
    this.product_name,
    this.punit_id,
    this.punit_name,
    this.punit_brief,
    this.punit_fpoint,
  });

  factory NewPurItemDto.fromJson(Map<String, dynamic> json) =>
      _$NewPurItemDtoFromJson(json);
  Map<String, dynamic> toJson() => _$NewPurItemDtoToJson(this);
}
