// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import 'package:shopping_list_flutter/network/incoming/pur_item_dto.dart';

part 'purchase_filled_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PurchaseFilledDto {
  int id;
  int room;
  int message;

  // bool purchased;
  // int? person_purchased;
  // String? person_purchased_name;

  List<PurItemDto> purItems;

  PurchaseFilledDto({
    required this.id,
    required this.room,
    required this.message,
    // required this.purchased,
    // this.person_purchased,
    // this.person_purchased_name,
    required this.purItems,
  });

  factory PurchaseFilledDto.fromJson(Map<String, dynamic> json) =>
      _$PurchaseFilledDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PurchaseFilledDtoToJson(this);
}
