// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import 'package:shopping_list_flutter/network/incoming/purchase/pur_item_dto.dart';

part 'new_pur_item_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: false,
    includeIfNull: true)
class NewPurItemDto {
  String name;
  double? qnty;

  String? comment;

  int? pgroup_id;
  String? pgroup_name;

  int? product_id;
  String? product_name;

  int? punit_id;
  String? punit_name;

  String? punit_brief;
  bool? punit_fpoint;

  NewPurItemDto({
    required this.name,
    this.qnty,
    this.comment,
    this.pgroup_id,
    this.pgroup_name,
    this.product_id,
    this.product_name,
    this.punit_id,
    this.punit_name,
    this.punit_brief,
    this.punit_fpoint,
  });

  static NewPurItemDto fromPurItem(PurItemDto purItem) {
    return NewPurItemDto(
      name: purItem.name,
      qnty: purItem.qnty,
      comment: purItem.comment,
      pgroup_id: purItem.pgroup_id,
      pgroup_name: purItem.pgroup_name,
      product_id: purItem.product_id,
      product_name: purItem.product_name,
      punit_id: purItem.punit_id,
      punit_name: purItem.punit_name,
      punit_brief: purItem.punit_brief,
      punit_fpoint: purItem.punit_fpoint,
    );
  }

  factory NewPurItemDto.fromJson(Map<String, dynamic> json) =>
      _$NewPurItemDtoFromJson(json);
  Map<String, dynamic> toJson() => _$NewPurItemDtoToJson(this);
}
