// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';
import 'package:shopping_list_flutter/network/incoming/purchase/pur_item_dto.dart';
import 'package:shopping_list_flutter/network/incoming/purchase/purchase_dto.dart';

part 'pur_item_fill_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PurItemFillDto {
  int id;
  String name;
  int room;
  int message;
  int purchase;

  int bought;
  double? bought_qnty;
  double? bought_price;
  double? bought_weight;
  String? comment;

  PurItemFillDto({
    required this.id,
    required this.name,
    required this.room,
    required this.message,
    required this.purchase,
    required this.bought,
    this.bought_qnty,
    this.bought_price,
    this.bought_weight,
    this.comment,
  });

  static PurItemFillDto fromPurItem(PurItemDto purItem, PurchaseDto purchase) {
    return PurItemFillDto(
        id: purItem.id,
        name: purItem.name,
        room: purchase.room,
        message: purchase.message,
        purchase: purchase.id,
        bought: purItem.bought,
        bought_qnty: purItem.bought_qnty,
        bought_price: purItem.bought_price,
        bought_weight: purItem.bought_weight,
        comment: purItem.comment);
  }

  factory PurItemFillDto.fromJson(Map<String, dynamic> json) =>
      _$PurItemFillDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PurItemFillDtoToJson(this);
}
