// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build --archive-conflicting-outputs
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'archive_messages_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class ArchiveMessagesDto {
  List<int> messageIds;
  bool archived;
  int user;

  ArchiveMessagesDto(
      {required this.messageIds, required this.archived, required this.user});

  factory ArchiveMessagesDto.fromJson(Map<String, dynamic> json) =>
      _$ArchiveMessagesDtoFromJson(json);
  Map<String, dynamic> toJson() => _$ArchiveMessagesDtoToJson(this);
}
