// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'delete_room_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: false,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class DeleteRoomDto {
  int roomId;
  int personIdShouldBeAdmin;

  DeleteRoomDto({required this.roomId, required this.personIdShouldBeAdmin});

  // factory DeleteRoomDto.fromJson(Map<String, dynamic> json) =>
  //     _$DeleteRoomDtoFromJson(json);
  Map<String, dynamic> toJson() => _$DeleteRoomDtoToJson(this);
}
