// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

import '../../incoming/room/room_member_dto.dart';

part 'edit_room_members_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: false,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class EditRoomMembersDto {
  int personEditing;
  String? personEditing_name;
  int roomId;
  List<RoomMemberDto>? personsToChangePermissions;
  List<RoomMemberDto>? personsToAdd;
  String? welcomeMsg;
  List<RoomMemberDto>? personsToRemove;
  String? goodByeMsg;

  EditRoomMembersDto(
      {required this.personEditing,
      this.personEditing_name,
      required this.roomId,
      this.personsToChangePermissions,
      this.personsToAdd,
      this.welcomeMsg,
      this.personsToRemove,
      this.goodByeMsg});

  // factory EditRoomMembersDto.fromJson(Map<String, dynamic> json) =>
  //     _$EditRoomMembersDtoFromJson(json);
  Map<String, dynamic> toJson() => _$EditRoomMembersDtoToJson(this);
}
