// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'leave_room_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: false,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class LeaveRoomDto {
  int roomId;
  int personIdLeaving;

  LeaveRoomDto({required this.roomId, required this.personIdLeaving});

  // factory LeaveRoomDto.fromJson(Map<String, dynamic> json) =>
  //     _$LeaveRoomDtoFromJson(json);
  Map<String, dynamic> toJson() => _$LeaveRoomDtoToJson(this);
}
