// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'rename_room_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class RenameRoomDto {
  int id;
  String newName;

  RenameRoomDto({required this.id, required this.newName});

  factory RenameRoomDto.fromJson(Map<String, dynamic> json) =>
      _$RenameRoomDtoFromJson(json);
  Map<String, dynamic> toJson() => _$RenameRoomDtoToJson(this);
}
