// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'room_persons_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: false,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class RoomPersonsDto {
  int roomId;
  List<int> personIds;

  RoomPersonsDto({required this.roomId, required this.personIds});

  // factory RoomPersonsDto.fromJson(Map<String, dynamic> json) =>
  //     _$RoomPersonsDtoFromJson(json);
  Map<String, dynamic> toJson() => _$RoomPersonsDtoToJson(this);
}
