// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

part 'pur_item_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PurItemDto {
  int id;
  // DateTime date_created;
  // DateTime date_updated;

  String name;
  double? qnty;

  String? comment;

  int? pgroup_id;
  String? pgroup_name;

  int? product_id;
  String? product_name;

  int? punit_id;
  String? punit_name;

  String? punit_brief;
  bool? punit_fpoint;

  int bought;
  double? bought_qnty;
  double? bought_price;
  double? bought_weight;

  PurItemDto({
    required this.id,
    // required this.date_created,
    // required this.date_updated,
    required this.name,
    this.qnty,
    this.comment,
    this.pgroup_id,
    this.pgroup_name,
    this.product_id,
    this.product_name,
    this.punit_id,
    this.punit_name,
    this.punit_brief,
    this.punit_fpoint,
    required this.bought,
    this.bought_qnty,
    this.bought_price,
    this.bought_weight,
  });

  factory PurItemDto.fromJson(Map<String, dynamic> json) =>
      _$PurItemDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PurItemDtoToJson(this);
}
