// DTO regenerated by https://pub.dev/documentation/json_annotation/latest/json_annotation/JsonSerializable/explicitToJson.html
// $ flutter pub run build_runner build
// $ flutter pub run build_runner watch

import 'package:json_annotation/json_annotation.dart';

import 'pur_item_dto.dart';

part 'purchase_dto.g.dart';

@JsonSerializable(
    checked: true,
    createFactory: true,
    createToJson: true,
    explicitToJson: true,
    disallowUnrecognizedKeys: true,
    includeIfNull: true)
class PurchaseDto {
  int id;
  DateTime date_created;
  DateTime date_updated;
  String name;

  int room;
  int message;

  int show_pgroup;
  int show_price;
  int show_qnty;
  int show_weight;

  int person_created;
  String person_created_name;
  int? person_purchased;
  String? person_purchased_name;

  double? price_total;
  double? weight_total;

  List<PurItemDto> purItems;

  PurchaseDto({
    required this.id,
    required this.date_created,
    required this.date_updated,
    required this.name,
    required this.room,
    required this.message,
    required this.show_pgroup,
    required this.show_price,
    required this.show_qnty,
    required this.show_weight,
    required this.person_created,
    required this.person_created_name,
    this.person_purchased,
    this.person_purchased_name,
    this.price_total,
    this.weight_total,
    required this.purItems,
  });

  factory PurchaseDto.fromJson(Map<String, dynamic> json) =>
      _$PurchaseDtoFromJson(json);
  Map<String, dynamic> toJson() => _$PurchaseDtoToJson(this);
}
